---

- name: Check if Gnome Shell extension is already installed - {{ gnome_extension_info.name }}
  stat:
    path: "/home/goliat/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}/metadata.json"
  register: r_gnome_extensions_check_existing

#- name: Create temporary download directory
#  tempfile:
#    state: directory
#    suffix: ".gnome_extension_download"
#  register: r_gnome_extension_download_dir
#  changed_when: no
#  when: r_gnome_extensions_check_existing.stat.exists == False

- name: Download Gnome Shell extension - {{ gnome_extension_info.name }}
  get_url:
    url: https://extensions.gnome.org{{ gnome_extension_info.download_url }}
    dest: "/tmp/{{ gnome_extension_info.uuid }}.zip"
  register: r_gnome_extension_download

- name: Create install directory - {{ gnome_extension_info.name }}
  file:
    path: "/home/goliat/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
    state: directory
    owner: goliat
    group: goliat
    mode: 0775

- name: Install Gnome Shell extension - {{ gnome_extension_info.name }}
  become: yes
  become_user: goliat
  unarchive:
    src: "{{ r_gnome_extension_download.dest }}"
    dest: "/home/goliat/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
    remote_src: yes

- name: Enable Gnome Shell extension - {{ gnome_extension_info.name }} - {{ gnome_extension_info.uuid }}
  become: yes
  become_user: goliat
  ansible.builtin.command: gnome-extensions enable {{ gnome_extension_info.uuid }}
#  always:
#    - name: Delete temporary download directory
#      file:
#        path: "{{ r_gnome_extension_download_dir.path }}"
#        state: absent
#      changed_when: no
#  when: r_gnome_extensions_check_existing.stat.exists == False