---
- hosts: localhost
  connection: local
  become: true
  vars:
    gnome_extension_ids:
      - 1160

  tasks:
  
  - include_tasks: System_Settings/repos.yml

  - include_tasks: program/docker.yml
  - include_tasks: program/gnome-shell-devel.yml
  - include_tasks: program/go.yml
  - include_tasks: program/onedrive.yml
  - include_tasks: program/remmina.yml
  - include_tasks: program/msEdge.yml
  - include_tasks: program/spotify.yml
  - include_tasks: program/obs-studio.yml
  - include_tasks: program/vsCode.yml
  - include_tasks: program/virtualbox.yml
  - include_tasks: program/teams.yml
  - include_tasks: program/cronie.yml

  - name: add ansible user
    user:
      name: ansible_user
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible_user
      dest: /etc/sudoers.d/ansible_user
      owner: root
      group: root
      mode: 0440
 
  - name: add ansible-pull cron job
    ansible.builtin.cron:
      name: ansible auto-provision
      user: ansible_user
      minute: "*/2"
      job: "ansible-pull -o -U https://github.com/Gooliat/asible_desktop.git"

  - name: copy wallpaper file
    copy:
      src: files/openSUSE.png
      dest: /usr/share/wallpapers/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper-light
    become_user: goliat
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/wallpapers/ansible-wallpaper.png'"

  - name: set wallpaper-dark
    become_user: goliat
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/wallpapers/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: goliat
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'centered'"

  - name: Parse Gnome Shell version
    shell: gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
    register: r_gnome_extension_parse_shell_version
    changed_when: no

  - set_fact:
      gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"

  - name: Get Gnome Shell extension info
    uri:
      url: https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnome_shell_version }}
      return_content: yes
    loop: "{{ gnome_extension_ids }}"
    register: r_gnome_extension_info
    ignore_errors: yes

  - include_tasks: install_extension.yml
    vars:
      gnome_extension_info: "{{ item.json }}"
    loop: "{{ r_gnome_extension_info.results }}"
    when: item.status == 200