- name: Add zypper signing key
  ansible.builtin.rpm_key:
    key: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add repository into repo.d list
  zypper_repository:
    name: microsoft-edge-dev
    repo: "https://packages.microsoft.com/yumrepos/edge"
    enabled: true
    autorefresh: yes
    auto_import_keys: yes
    runrefresh: yes

- name: Install microsoft-edge-dev
  package:
    name: "microsoft-edge-dev"