- name: Add zypper signing key
  ansible.builtin.rpm_key:
    key: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add repository into repo.d list
  zypper_repository:
    name: microsoft-edge
    baseurl: "https://packages.microsoft.com/yumrepos/edge/"
    enabled: true
    auto_import_keys: yes

- name: Install microsoft-edge-stable
  package:
    name: "microsoft-edge-dev"
    state: latest
    update_cache: true
